# Generated by Django 4.2.7 on 2023-11-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='op', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
