# Generated by Django 4.2.7 on 2023-11-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAcc',
        ),
    ]
