# Generated by Django 4.2.7 on 2023-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_remove_user_email_user_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
